# Generated by Django 4.2 on 2025-11-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0002_category_transaction"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-date"]},
        ),
        migrations.AddField(
            model_name="transaction",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the transaction",
                null=True,
            ),
        ),
    ]
