# Generated by Django 4.2 on 2025-11-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0003_alter_transaction_options_transaction_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("income", "Доход"), ("expense", "Расход")], max_length=7
            ),
        ),
    ]
