# Generated by Django 4.2 on 2025-11-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0004_alter_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.TextField(
                blank=True, help_text="Описание транзакции", null=True
            ),
        ),
    ]
